---
title: "05_visualising"
author: "Astrid Elmann Hansen"
date: '2023-01-06'
output: html_document
---

```{r}
pacman::p_load(tidyverse)

# loading files
df <- read_csv("data/fv_22_kandidat_test.csv")
ans <- read_csv("data/answers.csv")

df$education <- factor(df$education,
                  levels = c("Ikke oplyst", 
                             "Grundskole", 
                             "10. klasse",
                             "Gymnasial uddannelse",                             
                             "Erhvervsuddannelse",
                             "Seminaruddannelse",
                             "Bachelor-/diplomuddannelse",
                             "Kandidat-/masteruddannelse",
                             "Ph.d.-uddannelse"
                             ))
```

# Investigating the candidates
#Looking at education levels

```{r}
df %>% 
  ggplot(aes(x = education, fill = elected)) + 
  geom_bar() +
  coord_flip()
```

```{r}
df %>% filter(education == "Ikke oplyst" |
              education == "Erhvervsuddannelse" |
              #education == "Grundskole" |
              #education == "10. klasse" |
              education == "Gymnasial uddannelse" |
              education == "Seminaruddannelse" |
              #education == "Bachelor-/diplomuddannelse" |
              education == "Kandidat-/masteruddannelse") %>%  #|
              #education == "Ph.d.-uddannelse") %>% 
  ggplot(aes(x = education, fill = elected)) + 
  geom_bar() +
  coord_flip() +
  ggtitle("5 most common education levels among candidates")
```


```{r}
unique(df$profession)

df %>% ggplot(aes(x = profession)) +
  geom_bar()


df %>% 
	group_by(profession) %>% 
	summarise(count = n()) %>% 
	ggplot(aes(x = reorder(profession,(-count)), y = count)) + 
	geom_bar(stat = 'identity') +
  coord_flip()


```


# Is a candidate elected based on...
## ...whether they participated in the candidate test?
```{r}
df %>% ggplot(aes(x = participated, y = elected)) +
  geom_jitter()
```

## ...a strong conviction when answering questions
```{r}
df %>% ggplot(aes(x = conviction, fill = elected)) +
  geom_density(alpha = 0.5) +
  theme_bw() +
  ggtitle("Density plot of candidates conviction") +
  labs(x = "Conviction %",
       y = "Density",
       fill = 'Elected') 
  
```

## ...the number of notes?
```{r}
df %>% ggplot(aes(x = no_notes, y = elected, color = elected)) +
  geom_jitter()
```

## ...average length of notes?
```{r}
df %>% ggplot(aes(x = avg_note_len, y = elected, color = elected)) +
  geom_jitter()
```

# What are the most dividing questions?

```{r}
i <- 1
for (q in ans[2:26]){
p <- ans %>% ggplot(aes(x = q)) + 
  geom_histogram() +
  ggtitle(paste0("Q no ", i))
i = i+1
print(p)
}
```




